version: '{build}'

skip_tags: true

environment:
  matrix:
    - ruby_version: "200"

cache:
  - vendor/bundle

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler
  - bundler --version
  - bundle platform
  - bundle install --path=vendor/bundle --retry=3 --jobs=3

test_script:
  - bundle exec rake test

build: off
